[build]
  command = "npm run build && npm run export"
  functions = "netlify/functions"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"  # Change from 18 to 20

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"